#index:
#    path: /
#    controller: App\Controller\DefaultController::index


author:
    path: /author
    controller: App\Controller\AuthorController::index

authors:
    path: /authors
    controller: App\Controller\AuthorController::list    

authorDetails:
    path: /authors/{id}
    controller: App\Controller\AuthorController::authorDetails    